#! /usr/bin/env sh

yabai -m config layout bsp
yabai -m config auto_balance off
yabai -m config window_gap -20
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0

# make focus keyboard friendly
yabai -m config focus_follows_mouse on

yabai -m config window_placement about_equal
yabai -m config window_topmost on
yabai -m config window_shadow float

yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_follows_focus off
yabai -m config window_origin_display default

yabai -m config auto_balance off

yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_drop_action stack

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
